on: [ push, pull_request ]
name: Build & Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependency libraries
        run: sudo apt-get install -y libgpgme-dev libdevmapper-dev build-essential pkg-config libbtrfs-dev
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./... -tags integration
